sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
      PACKAGE_SERVER_IP: 50.211.244.129
      REPOSITORY: buster
      PKGTOOLS_COMMIT: origin/${TRAVIS_BRANCH}
      UPLOAD: scp
  jobs:
    - ARCHITECTURE: amd64
    - ARCHITECTURE: i386
    - ARCHITECTURE: arm64

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-build-multiarch
- openssl aes-256-cbc -K $encrypted_43711b6157b7_key -iv $encrypted_43711b6157b7_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

script:
- docker-compose -f docker-compose.build.yml run pkgtools
- docker-compose -f docker-compose.build.yml run build

notifications:
  email: false
  slack:
    rooms:
      - secure: 3xz4osSL/cTQjO7ojlLKho+d3isesSyqe9Uo5y1mNvQGhxuFthU0bhQl3sGXdyNSYy4tfFEIgViRpY83EjYzJKByDHSpdtRAi+9GnCtEPvzQtUj18LHpdVjLrRKQF4BnDzd4awGfBKV4UFGk+qeuTlQt2AtqvutLff1Cw2vyB30zuRo93lRK/cxKgerKBziTgepZCE1Mcc1X0lPUY99sQ95YQzizk9DQoh8tYmkdKbmOxJ2moAVgKFxZVi6TbEyROJnFDZgIL7TYL4Rda9XIHYpy1FgNMlcH/RICPfx0RCUzvUL3V+YCMXxQWg8oU0t5DwG6QE+CAjMfvC3WsZQDU36avJVw0BGLwjiGppILInYyMzndr398Jfi+9suzYAV9FoGI7Hts6PjqoOc6826qrR0wWV5Na+F+zM5Wxgv12zHlR+LU7ecmUUJNqUM2Hip9FKtIy0aeFWR2/xZMQiDLEMzls33JNXiRGtFPjxMeDv0iBa2FcEJu8v9jZXRopQSHLsWXAPZN+2Y14XcRyvG6Mfpo5+mpgjzQtpWmTWmiRip32eB6PU9wG50hB2Xhg4RAeJCNXIPPl3OhIo67op2tQBXbf4gkaMA1gsjWS+W4BtH+o4m8/HdEDur04Go0DDOqD9gpK4/3S02qYiDiLJY8v6SOzTubbwr6+Q6Dsj30sRE=
    on_success: always
    on_failure: always
